export const FILL_SIGNUP_ACTION_TYPES = 'FILL_SIGNUP_ACTION_TYPES' as const;

export const FLUSH_SIGNUP_ACTION_TYPES = 'FLUSH_SIGNUP_ACTION_TYPES' as const;

export const SETUP_SIGNUP_TYPE_ACTION_TYPES =
  'SETUP_SIGNUP_TYPE_ACTION_TYPES' as const;
