export const UPDATE_MEMO_ACTION_TYPE = 'UPDATE_MEMO_ACTION_TYPE' as const;

export const ADD_MEMO_ACTION_TYPE = 'ADD_MEMO_ACTION_TYPE' as const;

export const CLEAR_MEMO_ACTION_TYPE = 'CLEAR_MEMO_ACTION_TYPE' as const;
