const images = {
  components: {
    common: {
      back: require('./images/components/common/ic-back.png'),
      check: require('./images/components/common/ic-check.png'),
      passwordHide: require('./images/components/common/ic-password-hide.png'),
      passwordShow: require('./images/components/common/ic-password-show.png'),
      unChecked: require('./images/components/common/ic-unchecked.png'),
      close: require('./images/components/common/ic-close.png'),
      like: require('./images/components/common/ic-like.png'),
      unlike: require('./images/components/common/ic-unlike.png'),
    },
    Splash: {
      line: require('./images/components/Splash/ic-splash-line.png'),
      text: require('./images/components/Splash/ic-splash-text.png'),
    },
    Login: {
      label: require('./images/components/Login/ic-label.png'),
      kakao: require('./images/components/Login/ic-kakao.png'),
    },
    Signup: {
      done: require('./images/components/Signup/ic-done.png'),
    },
    Mbti: {
      back: require('./images/components/Mbti/ic-primary-back.png'),
      text: require('./images/components/Mbti/ic-text.png'),
      icon1: require('./images/components/Mbti/ic-icon-1.png'),
      icon2: require('./images/components/Mbti/ic-icon-2.png'),
      icon3: require('./images/components/Mbti/ic-icon-3.png'),
      icon4: require('./images/components/Mbti/ic-icon-4.png'),
      icon5: require('./images/components/Mbti/ic-icon-5.png'),
      icon6: require('./images/components/Mbti/ic-icon-6.png'),
      icon7: require('./images/components/Mbti/ic-icon-7.png'),
      icon8: require('./images/components/Mbti/ic-icon-8.png'),
    },
    Diary: {
      triangle: require('./images/components/Diary/ic-tri.png'),
      add: require('./images/components/Diary/ic-add.png'),
      weather1: require('./images/components/Diary/ic-weather-1.png'),
      weather2: require('./images/components/Diary/ic-weather-2.png'),
      weather3: require('./images/components/Diary/ic-weather-3.png'),
      weather4: require('./images/components/Diary/ic-weather-4.png'),
      weather5: require('./images/components/Diary/ic-weather-5.png'),
      emotion1: require('./images/components/Diary/ic-emotion-1.png'),
      emotion2: require('./images/components/Diary/ic-emotion-2.png'),
      emotion3: require('./images/components/Diary/ic-emotion-3.png'),
      emotion4: require('./images/components/Diary/ic-emotion-4.png'),
      emotion5: require('./images/components/Diary/ic-emotion-5.png'),
      emotion6: require('./images/components/Diary/ic-emotion-6.png'),
    },
    HangangNow: {
      char1: require('./images/components/HangangNow/ic-char-1.png'),
      char2: require('./images/components/HangangNow/ic-char-2.png'),
      char3: require('./images/components/HangangNow/ic-char-3.png'),
      char4: require('./images/components/HangangNow/ic-char-4.png'),
      char5: require('./images/components/HangangNow/ic-char-5.png'),
      char6: require('./images/components/HangangNow/ic-char-6.png'),
      map: require('./images/components/HangangNow/ic-map.png'),
      car: require('./images/components/HangangNow/ic-car.png'),
    },
    MyPage: {
      placeholder: require('./images/components/MyPage/ic-ph-profile.png'),
      rightArrow: require('./images/components/MyPage/ic-right-arrow.png'),
      setting: require('./images/components/MyPage/ic-setting.png'),
      prev: require('./images/components/MyPage/ic-prev.png'),
      next: require('./images/components/MyPage/ic-next.png'),
      add: require('./images/components/MyPage/ic-add.png'),
      checked: require('./images/components/MyPage/ic-checked.png'),
    },
    Home: {
      mainbanner: require('./images/components/Home/ic-home-banner.png'),
      prev: require('./images/components/Home/ic-prev.png'),
      next: require('./images/components/Home/ic-next.png'),
    },
    Leaflet: {
      downArrow: require('./images/components/Leaflet/ic-down-arrow.png'),
    },
    ParkDetail: {
      image1: require('./images/components/ParkDetail/ic-park-1.png'),
      image2: require('./images/components/ParkDetail/ic-park-2.png'),
      image3: require('./images/components/ParkDetail/ic-park-3.png'),
      image4: require('./images/components/ParkDetail/ic-park-4.png'),
      image5: require('./images/components/ParkDetail/ic-park-5.png'),
      image6: require('./images/components/ParkDetail/ic-park-6.png'),
      image7: require('./images/components/ParkDetail/ic-park-7.png'),
      image8: require('./images/components/ParkDetail/ic-park-8.png'),
      image9: require('./images/components/ParkDetail/ic-park-9.png'),
      image10: require('./images/components/ParkDetail/ic-park-10.png'),
      image11: require('./images/components/ParkDetail/ic-park-11.png'),
    },
    Facility: {
      line: require('./images/components/Facility/ic-line.png'),
      category1: require('./images/components/Facility/ic-category-1.png'),
      category2: require('./images/components/Facility/ic-category-2.png'),
      category3: require('./images/components/Facility/ic-category-3.png'),
      category4: require('./images/components/Facility/ic-category-4.png'),
      category5: require('./images/components/Facility/ic-category-5.png'),
      category6: require('./images/components/Facility/ic-category-6.png'),
      category7: require('./images/components/Facility/ic-category-7.png'),
      category8: require('./images/components/Facility/ic-category-8.png'),
      category9: require('./images/components/Facility/ic-category-9.png'),
      category10: require('./images/components/Facility/ic-category-10.png'),
      category11: require('./images/components/Facility/ic-category-11.png'),
      category12: require('./images/components/Facility/ic-category-12.png'),
      category13: require('./images/components/Facility/ic-category-13.png'),
      category14: require('./images/components/Facility/ic-category-14.png'),
      category15: require('./images/components/Facility/ic-category-15.png'),
    },
    Trip: {
      ic1: require('./images/components/Trip/ic-1.png'),
      ic2: require('./images/components/Trip/ic-2.png'),
      ic3: require('./images/components/Trip/ic-3.png'),
      icFind1: require('./images/components/Trip/ic-find-1.png'),
      icFind2: require('./images/components/Trip/ic-find-2.png'),
      icFind4: require('./images/components/Trip/ic-find-4.png'),
    },
  },
  routes: {
    selected1: require('./images/routes/ic-selected-1.png'),
    selected2: require('./images/routes/ic-selected-2.png'),
    selected3: require('./images/routes/ic-selected-3.png'),
    selected4: require('./images/routes/ic-selected-4.png'),
    selected5: require('./images/routes/ic-selected-5.png'),
    unselected1: require('./images/routes/ic-unselected-1.png'),
    unselected2: require('./images/routes/ic-unselected-2.png'),
    unselected3: require('./images/routes/ic-unselected-3.png'),
    unselected4: require('./images/routes/ic-unselected-4.png'),
    unselected5: require('./images/routes/ic-unselected-5.png'),
  },
} as const;

export default images;
